import { useState } from 'react'
import HowToPlay from '../HowToPlay'
import NumberStepper from '../NumberStepper'
import AiCustomOption from '../AiCustomOption'
import { ROUND_MIN, ROUND_MAX, ROUND_DEFAULT, clampRounds } from '../roundConfig'

const PROMPTS_PER_PLAYER_OPTIONS = [1, 2]

export default function FibbageSetup({
  gameId,
  playerCount,
  saved,
  onStart,
  onCancel,
  error,
  submitLabel,
  aiContent = {},
  aiEnabled = false,
  onGenerateContent,
}) {
  const customTopics = aiContent[gameId] ?? [] // AI topic names this session

  // Pre-fill from the host's last settings for this game this room.
  const [mode, setMode] = useState(() =>
    saved?.mode === 'personal' || saved?.mode === 'custom' ? saved.mode : 'bank',
  )
  const [rounds, setRounds] = useState(() => clampRounds(saved?.rounds ?? ROUND_DEFAULT))
  const [promptsPerPlayer, setPromptsPerPlayer] = useState(() =>
    PROMPTS_PER_PLAYER_OPTIONS.includes(saved?.promptsPerPlayer) ? saved.promptsPerPlayer : 1,
  )
  const [topic, setTopic] = useState(() =>
    customTopics.includes(saved?.topic) ? saved.topic : null,
  )

  const notEnough = playerCount < 3
  const estimatedRounds = playerCount * promptsPerPlayer
  const customNoTopic = mode === 'custom' && !topic

  function start() {
    if (mode === 'personal') onStart({ mode: 'personal', promptsPerPlayer })
    else if (mode === 'custom') onStart({ mode: 'custom', topic, rounds })
    else onStart({ mode: 'bank', rounds })
  }

  return (
    <div className="screen setup-screen">
      <h1 className="title">Fact or Fake</h1>
      <HowToPlay gameId={gameId} />
      <p className="hint hint-block">
        Everyone writes a fake answer to blend in with the real one, then votes
        for which answer they think is true. Fool people with your fake, and
        spot the truth yourself.
      </p>

      <div>
        <span className="label">Question source</span>
        <div className="pill-group pill-group-wrap">
          <button
            type="button"
            className={`pill ${mode === 'bank' ? 'pill-active' : ''}`}
            onClick={() => setMode('bank')}
          >
            Trivia bank
          </button>
          <button
            type="button"
            className={`pill ${mode === 'personal' ? 'pill-active' : ''}`}
            onClick={() => setMode('personal')}
          >
            Personal Mode
          </button>
        </div>
        {mode === 'personal' ? (
          <p className="hint hint-block">
            Rounds are built from players' real answers about themselves — a
            test of how well you know each other. Each player answers a prompt
            or two privately; then everyone tries to fake each other's answers.
          </p>
        ) : mode === 'custom' ? (
          <p className="hint hint-block">
            Obscure true facts about a topic you choose, generated by the app
            and kept in this room for the session.
          </p>
        ) : (
          <p className="hint hint-block">
            Obscure true facts from the built-in bank, drawn at random with no
            repeats within a game.
          </p>
        )}
      </div>

      {aiEnabled && (
        <div>
          <span className="label">Custom topic</span>
          {customTopics.length > 0 && (
            <div className="pill-group pill-group-wrap">
              {customTopics.map((name) => (
                <button
                  key={name}
                  type="button"
                  className={`pill ${mode === 'custom' && topic === name ? 'pill-active' : ''}`}
                  onClick={() => {
                    setMode('custom')
                    setTopic(name)
                  }}
                >
                  {name}
                </button>
              ))}
            </div>
          )}
          <AiCustomOption
            label="Custom Topic"
            placeholder="Ancient Rome"
            noun="fact set"
            hint="Name a topic (e.g. “Deep Sea Creatures”, “The Roman Empire”). The app builds a batch of obscure true facts for it."
            onGenerate={(name, cb) => onGenerateContent(gameId, name, cb)}
            onGenerated={(name) => {
              setMode('custom')
              setTopic(name)
            }}
          />
        </div>
      )}

      {mode === 'personal' ? (
        <div>
          <span className="label">Prompts per player</span>
          <div className="pill-group">
            {PROMPTS_PER_PLAYER_OPTIONS.map((n) => (
              <button
                key={n}
                type="button"
                className={`pill ${promptsPerPlayer === n ? 'pill-active' : ''}`}
                onClick={() => setPromptsPerPlayer(n)}
              >
                {n}
              </button>
            ))}
          </div>
          <p className="hint hint-block">
            Everyone answers {promptsPerPlayer} prompt{promptsPerPlayer === 1 ? '' : 's'}{' '}
            (~45s each) — about {estimatedRounds} rounds total, one per answer.
          </p>
        </div>
      ) : (
        <NumberStepper
          label="How many rounds?"
          value={rounds}
          min={ROUND_MIN}
          max={ROUND_MAX}
          onChange={setRounds}
        />
      )}

      {notEnough && (
        <p className="hint">Fact or Fake needs at least 3 players.</p>
      )}
      {customNoTopic && (
        <p className="hint">Generate or pick a custom topic to start.</p>
      )}
      {error && <p className="error">{error}</p>}

      <button
        className="btn btn-start"
        onClick={start}
        disabled={notEnough || customNoTopic}
      >
        {submitLabel ?? 'Start Game'}
      </button>
      <button className="btn btn-text" onClick={onCancel}>
        ← Back
      </button>
    </div>
  )
}
